[General]
edge = bottom
margin = 10

[MusicPlayer]
preference = spotify,vlc,firefox,chromium,mpd,rhythmbox,strawberry

[Keybinds]
toggle_visibility = Super+Shift+M
toggle_expand = Super+M

[Notifications]
enabled = true
now_playing = true

[Visualizer]
enabled = true
idle_timeout = 30

[VerticalDisplay]
enabled = true
idle_timeout = 5
