font_family									Hack Nerd Font
italic_font      								auto
bold_font        								auto
bold_italic_font 								auto
font_size        								9.5

adjust_line_height 						0
adjust_column_width 					0
box_drawing_scale 						0.001, 1, 1.5, 2
