include colors.conf
include keys.conf
include fonts.conf
include window.conf

# Scrollback
scrollback_lines 							10000
scrollback_pager 							usr/bin/less
wheel_scroll_multiplier 					5.0

# Performance
repaint_delay    							20
input_delay 								2
sync_to_monitor 							no

# Bell
visual_bell_duration 						0.0
enable_audio_bell 							yes
bell_on_tab									no

# Cursor
cursor_shape     							beam
cursor_blink_interval     					-1
cursor_stop_blinking_after 			15.0

# Tabs
tab_bar_edge 								bottom
tab_bar_style 								powerline
tab_bar_margin_width 					    0.0
tab_separator 								" ┇ "
active_tab_font_style 					    bold
inactive_tab_font_style 					normal
confirm_os_window_close 2

# URLs
url_style 									double
open_url_modifiers 						    ctrl+shift
open_url_with 								default
copy_on_select 								yes

# Selection
rectangle_select_modifiers 			        ctrl+shift
select_by_word_characters 			        #

# Mouse
click_interval 								0.5
mouse_hide_wait 							0
focus_follows_mouse 					    no

# Layouts
enabled_layouts 							*

# Shell
close_on_child_death 					    no
allow_remote_control 					    yes
term										xterm-kitty