$background = rgba(21274dff)
$foreground = rgba(c7c9d2ff)
$cursor = rgba(c7c9d2ff)
$color0 = rgba(21274dff)
$color1 = rgba(662B99ff)
$color2 = rgba(3B549Fff)
$color3 = rgba(952EA9ff)
$color4 = rgba(F9128Fff)
$color5 = rgba(F616A2ff)
$color6 = rgba(DD63ABff)
$color7 = rgba(c7c9d2ff)
$color8 = rgba(707388ff)
$color9 = rgba(662B99ff)
$color10 = rgba(3B549Fff)
$color11 = rgba(952EA9ff)
$color12 = rgba(F9128Fff)
$color13 = rgba(F616A2ff)
$color14 = rgba(DD63ABff)
$color15 = rgba(c7c9d2ff)