$background = rgba(544561ff)
$foreground = rgba(e2cfddff)
$cursor = rgba(e2cfddff)
$color0 = rgba(544561ff)
$color1 = rgba(B0A5BAff)
$color2 = rgba(C3A6BEff)
$color3 = rgba(979EC1ff)
$color4 = rgba(97A9C2ff)
$color5 = rgba(B1AEC5ff)
$color6 = rgba(CBB1C8ff)
$color7 = rgba(e2cfddff)
$color8 = rgba(9e909aff)
$color9 = rgba(B0A5BAff)
$color10 = rgba(C3A6BEff)
$color11 = rgba(979EC1ff)
$color12 = rgba(97A9C2ff)
$color13 = rgba(B1AEC5ff)
$color14 = rgba(CBB1C8ff)
$color15 = rgba(e2cfddff)