$background = rgba(070118ff)
$foreground = rgba(f4e9c9ff)
$cursor = rgba(f4e9c9ff)
$color0 = rgba(070118ff)
$color1 = rgba(60045Eff)
$color2 = rgba(D94627ff)
$color3 = rgba(930356ff)
$color4 = rgba(E2054Dff)
$color5 = rgba(DE8157ff)
$color6 = rgba(361594ff)
$color7 = rgba(f4e9c9ff)
$color8 = rgba(aaa38cff)
$color9 = rgba(60045Eff)
$color10 = rgba(D94627ff)
$color11 = rgba(930356ff)
$color12 = rgba(E2054Dff)
$color13 = rgba(DE8157ff)
$color14 = rgba(361594ff)
$color15 = rgba(f4e9c9ff)