# Shell variables
# Generated by 'wal'
wallpaper='/home/fercho/.wallpapers/Linux/Desktop/linux-tux-minimal-4k-ra.jpg'

# Special
background='#16151d'
foreground='#c7c8cb'
cursor='#c7c8cb'

# Colors
color0='#16151d'
color1='#883AFE'
color2='#8444D9'
color3='#9943FE'
color4='#AE4EFE'
color5='#C65AFF'
color6='#D061FE'
color7='#c7c8cb'
color8='#8b8c8e'
color9='#883AFE'
color10='#8444D9'
color11='#9943FE'
color12='#AE4EFE'
color13='#C65AFF'
color14='#D061FE'
color15='#c7c8cb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
