# █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

exec-once = wmname LG3D

# Services
exec-once = QT_QPA_PLATFORM=xcb /usr/lib/vktablet/vktablet &
exec-once = eval $(/usr/bin/gnome-keyring-daemon --start --components=secrets,ssh,gpg); export SSH_AUTH_SOCK; export GPG_AGENT_INFO; export GNOME_KEYRING_CONTROL
exec-once = systemctl --user start hyprpolkitagent

# Tray
exec-once = nm-applet
exec-once = blueman-applet
exec-once = udiskie -t -A -N
exec-once = hyprwave

# Theme
exec-once = waypaper --restore
#exec-once = ~/.bin/theme/wal.sh
exec-once = swayosd-server
exec-once = dunst
#exec-once = hyprctl setcursor BrezeX-Dark 24