# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

#windowrule = suppressevent maximize, class:.*
#windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

#layerrule = blur, ^(wlogout)$
#layerrule = blur, logout_dialog

#windowrule = float, class:Eww

#layerrule = blur, swaync-control-center
#layerrule = ignorezero, swaync-notification-window
#layerrule = animation slide right, swaync-control-center


# File Dialog
# xdg-desktop-portal dialogs
windowrulev2 = float, class:^Xdg-desktop-portal-gtk$
windowrulev2 = center, class:^Xdg-desktop-portal-gtk$
windowrulev2 = size 60% 80%, class:^Xdg-desktop-portal-gtk$
windowrulev2 = noborder, class:^Xdg-desktop-portal-gtk$
windowrulev2 = noblur, class:^Xdg-desktop-portal-gtk$

windowrulev2 = float, class:^xdg-desktop-portal-gtk$
windowrulev2 = center, class:^xdg-desktop-portal-gtk$
windowrulev2 = size 60% 80%, class:^xdg-desktop-portal-gtk$
windowrulev2 = noborder, class:^xdg-desktop-portal-gtk$
windowrulev2 = noblur, class:^xdg-desktop-portal-gtk$


# swayosd-server
windowrulev2 = float,class:^(swayosd-server)$
windowrulev2 = pin,class:^(swayosd-server)$
windowrulev2 = noborder,class:^(swayosd-server)$
windowrulev2 = nofocus,class:^(swayosd-server)$
windowrulev2 = stayfocused,class:^(swayosd-server)$

#windowrulev2 = move 50% 8%,class:^(swayosd-server)$
#windowrulev2 = move 50% 50%,class:^(swayosd-server)$
windowrulev2 = move 40% 1%,class:^(swayosd-server)$

#Xdg-desktop-portal-gtk

#windowrulev2 = float, class:^thunar$

# Brave
#windowrulev2 = float, class:^brave$

# Firefox Picture in Picture
windowrulev2 = float, title:^Picture-in-Picture$
windowrulev2 = size 320 180, title:^Picture-in-Picture$
windowrulev2 = move 100%-335 100%-240, title:^Picture-in-Picture$
windowrulev2 = workspace current, title:^Picture-in-Picture$
windowrulev2 = pin, title:^Picture-in-Picture$

# windowrule = float true, match:class xdg-desktop-portal-g tk
# windowrule = border_size 1, match:class xdg-desktop-portal-gtk

# windowrule = float true, match:class Xdg-desktop-portal-gtk
# windowrule = border_size 0, match:class Xdg-desktop-portal-gtk
# windowrule = no_blur true, match:class Xdg-desktop-portal-gtk

# windowrulev = size 0.5 0.5, class xdg-desktop-portal-gtk

# windowrule = float true, match:class brave
# windowrule = border_size 1, match:class brave