--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/tmp/wallpaper"

-- Special
background="#0E1855"
foreground="#a5c2da"
cursor="#a5c2da"

-- Colors
color0="#0E1855"
color1="#662B99"
color2="#3B549F"
color3="#952EA9"
color4="#F9128F"
color5="#F616A2"
color6="#DD63AB"
color7="#a5c2da"
color8="#738798"
color9="#662B99"
color10="#3B549F"
color11="#952EA9"
color12="#F9128F"
color13="#F616A2"
color14="#DD63AB"
color15="#a5c2da"
