[colors]
background = '#0b0b198e'
black = '#0b0b19'
blue = '#6D6D70'
cursor = '#c2c2c5'
cyan = '#B29967'
foreground = '#c2c2c5'
green = '#7D7C82'
magenta = '#8E8E91'
red = '#9D9DA2'
tabs = '#c2c2c5'
tabs-active = '#ADADB0'
white = '#c2c2c5'
yellow = '#c2c2c5'
dim-black = '#0b0b198e'
dim-blue = '#6D6D708e'
dim-cyan = '#B299678e'
dim-foreground = '#c2c2c58e'
dim-green = '#7D7C828e'
dim-magenta = '#8E8E918e'
dim-red = '#9D9DA28e'
dim-white = '#ADADB08e'
dim-yellow = '#c2c2c58e'
light-black = '#6D6D70'
light-blue = '#B29967'
light-cyan = '#7D7C82'
light-foreground = '#8E8E91'
light-green = '#9D9DA2'
light-magenta = '#ADADB0'
light-red = '#c2c2c5'
light-white = '#6D6D70'
light-yellow = '#B29967'
