[colors.primary]
background = "#0b0b19"
foreground = "#c2c2c5"

[colors.cursor]
text = "#0b0b19"
cursor = "#c2c2c5"

[colors.vi_mode_cursor]
text = "#0b0b19"
cursor = "#c2c2c5"

[colors.search.matches]
foreground = "#0b0b19"
background = "#c2c2c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5a5a6e"
background = "#c2c2c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0b0b19"
red = "#6D6D70"
green = "#B29967"
yellow = "#7D7C82"
blue = "#8E8E91"
magenta = "#9D9DA2"
cyan = "#ADADB0"
white = "#c2c2c5"

[colors.bright]
black = "#5a5a6e"
red = "#6D6D70"
green = "#B29967"
yellow = "#7D7C82"
blue = "#8E8E91"
magenta = "#9D9DA2"
cyan = "#ADADB0"
white = "#c2c2c5"

[colors.dim]
black = "#c2c2c5"
red = "#6D6D70"
green = "#9D9DA2"
yellow = "#7D7C82"
blue = "#8E8E91"
magenta = "#B29967"
cyan = "#ADADB0"
white = "#5a5a6e"

