# Shell variables
# Generated by 'wal'
wallpaper='/tmp/wallpaper'

# Special
background='#35170f'
foreground='#f5eade'
cursor='#f5eade'

# Colors
color0='#35170f'
color1='#FFD26E'
color2='#0C44A5'
color3='#6C8DC0'
color4='#E3B198'
color5='#FED2AA'
color6='#FEDEC8'
color7='#f5eade'
color8='#aba39b'
color9='#FFD26E'
color10='#0C44A5'
color11='#6C8DC0'
color12='#E3B198'
color13='#FED2AA'
color14='#FEDEC8'
color15='#f5eade'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
