# Shell variables
# Generated by 'wal'
wallpaper='/tmp/wallpaper'

# Special
background='#0E1855'
foreground='#a5c2da'
cursor='#a5c2da'

# Colors
color0='#0E1855'
color1='#662B99'
color2='#3B549F'
color3='#952EA9'
color4='#F9128F'
color5='#F616A2'
color6='#DD63AB'
color7='#a5c2da'
color8='#738798'
color9='#662B99'
color10='#3B549F'
color11='#952EA9'
color12='#F9128F'
color13='#F616A2'
color14='#DD63AB'
color15='#a5c2da'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
