foreground         #c2c2c5
background         #0b0b19
background_opacity 1.0
cursor             #c2c2c5

active_tab_foreground     #0b0b19
active_tab_background     #c2c2c5
inactive_tab_foreground   #c2c2c5
inactive_tab_background   #0b0b19

active_border_color   #c2c2c5
inactive_border_color #0b0b19
bell_border_color     #144D72

color0       #0b0b19
color8       #5a5a6e
color1       #144D72
color9       #144D72
color2       #353A8E
color10      #353A8E
color3       #572D8B
color11      #572D8B
color4       #2B5C92
color12      #2B5C92
color5       #5B5FA3
color13      #5B5FA3
color6       #8B67B6
color14      #8B67B6
color7       #c2c2c5
color15      #c2c2c5
