[colors.primary]
background = "#0b0b19"
foreground = "#c2c2c5"

[colors.cursor]
text = "#0b0b19"
cursor = "#c2c2c5"

[colors.vi_mode_cursor]
text = "#0b0b19"
cursor = "#c2c2c5"

[colors.search.matches]
foreground = "#0b0b19"
background = "#c2c2c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5a5a6e"
background = "#c2c2c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0b0b19"
red = "#144D72"
green = "#353A8E"
yellow = "#572D8B"
blue = "#2B5C92"
magenta = "#5B5FA3"
cyan = "#8B67B6"
white = "#c2c2c5"

[colors.bright]
black = "#5a5a6e"
red = "#144D72"
green = "#353A8E"
yellow = "#572D8B"
blue = "#2B5C92"
magenta = "#5B5FA3"
cyan = "#8B67B6"
white = "#c2c2c5"

[colors.dim]
black = "#c2c2c5"
red = "#144D72"
green = "#5B5FA3"
yellow = "#572D8B"
blue = "#2B5C92"
magenta = "#353A8E"
cyan = "#8B67B6"
white = "#5a5a6e"

