--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/tmp/wallpaper"

-- Special
background="#0b0b19"
foreground="#c2c2c5"
cursor="#c2c2c5"

-- Colors
color0="#0b0b19"
color1="#144D72"
color2="#353A8E"
color3="#572D8B"
color4="#2B5C92"
color5="#5B5FA3"
color6="#8B67B6"
color7="#c2c2c5"
color8="#5a5a6e"
color9="#144D72"
color10="#353A8E"
color11="#572D8B"
color12="#2B5C92"
color13="#5B5FA3"
color14="#8B67B6"
color15="#c2c2c5"
