foreground   #a5c2da
background   #0E1855
cursor       #a5c2da

color0       #0E1855
color8       #738798
color1       #662B99
color9       #662B99
color2       #3B549F
color10      #3B549F
color3       #952EA9
color11      #952EA9
color4       #F9128F
color12      #F9128F
color5       #F616A2
color13      #F616A2
color6       #DD63AB
color14      #DD63AB
color7       #a5c2da
color15      #a5c2da
