--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/tmp/wallpaper"

-- Special
background="#0b0b19"
foreground="#c2c2c5"
cursor="#c2c2c5"

-- Colors
color0="#0b0b19"
color1="#6D6D70"
color2="#B29967"
color3="#7D7C82"
color4="#8E8E91"
color5="#9D9DA2"
color6="#ADADB0"
color7="#c2c2c5"
color8="#5a5a6e"
color9="#6D6D70"
color10="#B29967"
color11="#7D7C82"
color12="#8E8E91"
color13="#9D9DA2"
color14="#ADADB0"
color15="#c2c2c5"
