--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/tmp/wallpaper"

-- Special
background="#35170f"
foreground="#f5eade"
cursor="#f5eade"

-- Colors
color0="#35170f"
color1="#FFD26E"
color2="#0C44A5"
color3="#6C8DC0"
color4="#E3B198"
color5="#FED2AA"
color6="#FEDEC8"
color7="#f5eade"
color8="#aba39b"
color9="#FFD26E"
color10="#0C44A5"
color11="#6C8DC0"
color12="#E3B198"
color13="#FED2AA"
color14="#FEDEC8"
color15="#f5eade"
