--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/tmp/wallpaper"

-- Special
background="#250d25"
foreground="#e2c9e4"
cursor="#e2c9e4"

-- Colors
color0="#250d25"
color1="#A55FA3"
color2="#CB5CB0"
color3="#DF2ECF"
color4="#E451D8"
color5="#7691C5"
color6="#AD9BCF"
color7="#e2c9e4"
color8="#9e8c9f"
color9="#A55FA3"
color10="#CB5CB0"
color11="#DF2ECF"
color12="#E451D8"
color13="#7691C5"
color14="#AD9BCF"
color15="#e2c9e4"
