# Shell variables
# Generated by 'wal'
wallpaper="/tmp/wallpaper"

# Special
background='#0b0b19'
foreground='#c2c2c5'
cursor='#c2c2c5'

# Colors
color0='#0b0b19'
color1='#6D6D70'
color2='#B29967'
color3='#7D7C82'
color4='#8E8E91'
color5='#9D9DA2'
color6='#ADADB0'
color7='#c2c2c5'
color8='#5a5a6e'
color9='#6D6D70'
color10='#B29967'
color11='#7D7C82'
color12='#8E8E91'
color13='#9D9DA2'
color14='#ADADB0'
color15='#c2c2c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
