[colors]
background = '#21274d8e'
black = '#21274d'
blue = '#662B99'
cursor = '#c7c9d2'
cyan = '#3B549F'
foreground = '#c7c9d2'
green = '#952EA9'
magenta = '#F9128F'
red = '#F616A2'
tabs = '#c7c9d2'
tabs-active = '#DD63AB'
white = '#c7c9d2'
yellow = '#c7c9d2'
dim-black = '#21274d8e'
dim-blue = '#662B998e'
dim-cyan = '#3B549F8e'
dim-foreground = '#c7c9d28e'
dim-green = '#952EA98e'
dim-magenta = '#F9128F8e'
dim-red = '#F616A28e'
dim-white = '#DD63AB8e'
dim-yellow = '#c7c9d28e'
light-black = '#662B99'
light-blue = '#3B549F'
light-cyan = '#952EA9'
light-foreground = '#F9128F'
light-green = '#F616A2'
light-magenta = '#DD63AB'
light-red = '#c7c9d2'
light-white = '#662B99'
light-yellow = '#3B549F'
