[colors]
background = '#0b0b198e'
black = '#0b0b19'
blue = '#144D72'
cursor = '#c2c2c5'
cyan = '#353A8E'
foreground = '#c2c2c5'
green = '#572D8B'
magenta = '#2B5C92'
red = '#5B5FA3'
tabs = '#c2c2c5'
tabs-active = '#8B67B6'
white = '#c2c2c5'
yellow = '#c2c2c5'
dim-black = '#0b0b198e'
dim-blue = '#144D728e'
dim-cyan = '#353A8E8e'
dim-foreground = '#c2c2c58e'
dim-green = '#572D8B8e'
dim-magenta = '#2B5C928e'
dim-red = '#5B5FA38e'
dim-white = '#8B67B68e'
dim-yellow = '#c2c2c58e'
light-black = '#144D72'
light-blue = '#353A8E'
light-cyan = '#572D8B'
light-foreground = '#2B5C92'
light-green = '#5B5FA3'
light-magenta = '#8B67B6'
light-red = '#c2c2c5'
light-white = '#144D72'
light-yellow = '#353A8E'
