# pywal theme for ghostty

background = 0b0b19
foreground = c2c2c5
cursor-color = c2c2c5
selection-background = c2c2c5
selection-foreground = 0b0b19

palette = 0=#0b0b19
palette = 1=#6D6D70
palette = 2=#B29967
palette = 3=#7D7C82
palette = 4=#8E8E91
palette = 5=#9D9DA2
palette = 6=#ADADB0
palette = 7=#c2c2c5
palette = 8=#5a5a6e
palette = 9=#6D6D70
palette = 10=#B29967
palette = 11=#7D7C82
palette = 12=#8E8E91
palette = 13=#9D9DA2
palette = 14=#ADADB0
palette = 15=#c2c2c5
