# pywal theme for ghostty

background = 0b0b19
foreground = c2c2c5
cursor-color = c2c2c5
selection-background = c2c2c5
selection-foreground = 0b0b19

palette = 0=#0b0b19
palette = 1=#144D72
palette = 2=#353A8E
palette = 3=#572D8B
palette = 4=#2B5C92
palette = 5=#5B5FA3
palette = 6=#8B67B6
palette = 7=#c2c2c5
palette = 8=#5a5a6e
palette = 9=#144D72
palette = 10=#353A8E
palette = 11=#572D8B
palette = 12=#2B5C92
palette = 13=#5B5FA3
palette = 14=#8B67B6
palette = 15=#c2c2c5
