# pywal theme for ghostty

background = 21274d
foreground = c7c9d2
cursor-color = c7c9d2
selection-background = c7c9d2
selection-foreground = 21274d

palette = 0=#21274d
palette = 1=#662B99
palette = 2=#3B549F
palette = 3=#952EA9
palette = 4=#F9128F
palette = 5=#F616A2
palette = 6=#DD63AB
palette = 7=#c7c9d2
palette = 8=#707388
palette = 9=#662B99
palette = 10=#3B549F
palette = 11=#952EA9
palette = 12=#F9128F
palette = 13=#F616A2
palette = 14=#DD63AB
palette = 15=#c7c9d2
