#! /bin/sh
#       ██
#      ░██              ██████
#      ░██       ██████░██░░░██ ███     ██ ██████████  ██████  █████
#      ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██░░██░░█ ██░░░██
#      ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██ ░██ ░ ░██  ░░
#      ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██ ░██   ░██   ██
#      ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██░███   ░░█████
#      ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░ ░░░     ░░░░░


################################################################################
#                       AUTOSTART
################################################################################


killall -q sxhkd 
sxhkd &
$HOME/.bin/autostart.sh
wmname LG3D


################################################################################
#                       VARIABLES
################################################################################


alias bc='bspc config'
alias br='bspc rule'
 

################################################################################
#                       WORSPACES and MONITORS
################################################################################


bspc monitor ^1 -d "" "ﱅ" "" "" "" "" "" "" ""



################################################################################
#                       CONFIG
################################################################################


#   Borders
bc border_width 0
bspc config border_radius	2
bc borderless_monocle true

#   Random
bc split_ratio 0.50
bc single_monocle        false

#   Focus
bc pointer_follows_focus false
bc focus_follows_pointer false
bc pointer_action2 resize_corner

# Gaps
bc window_gap 1

#   Border Colors
. "${HOME}/.cache/wal/colors.sh"
bc normal_border_color "$color1"
bc active_border_color "$color2"
bc focused_border_color "$color4"
bc presel_feedback_color "$color1"


################################################################################
#                       RULES
################################################################################


br -a mpv state=tiled
br -a tint2 state=tiling
br -a Lxappearance state=floating
br -a Zathura state=tiled 
br -a zoom desktop='^5'
br -a Microsoft\ Teams\ -\ Insiders:\* state=tiled desktop='^5' 
br -a kitty desktop='^6'
br -a Nemo desktop='^3' follow on
br -a Code desktop='^4'
br -a firefox desktop='^1'
br -a Brave-browser desktop='^1'
br -a krita desktop='^7'
#br -a Joplin desktop='^2'
