#! /bin/sh
#       ██
#      ░██              ██████
#      ░██       ██████░██░░░██ ███     ██ ██████████  ██████  █████
#      ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██░░██░░█ ██░░░██
#      ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██ ░██ ░ ░██  ░░
#      ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██ ░██   ░██   ██
#      ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██░███   ░░█████
#      ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░ ░░░     ░░░░░


################################################################################
#                       AUTOSTART
################################################################################


killall -q sxhkd 
sxhkd &
$HOME/.bin/autostart.sh
wmname LG3D


################################################################################
#                       VARIABLES
################################################################################


alias bc='bspc config'
alias br='bspc rule'


################################################################################
#                       WORSPACES and MONITORS
################################################################################


bspc monitor ^1 -d "" "" "" "" "" ""  
bspc monitor ^2 -d "" "" "󰕼"


################################################################################
#                       CONFIG
################################################################################


#   Borders
bc border_width 3
bspc config border_radius	0
bc borderless_monocle true

#   Random
bc split_ratio 0.5
bc single_monocle        false

#   Focus
bc pointer_follows_focus true
bc focus_follows_pointer false       
bc pointer_action2 resize_corner

# Gaps
bc window_gap 2

#   Border Colors
. "${HOME}/.cache/wal/colors.sh"
bc normal_border_color "$color1"
bc active_border_color "$color2"
bc focused_border_color "$color4"
bc presel_feedback_color "$color1"


################################################################################
#                       RULES
################################################################################

# if don't know the class of an aplication use the 
# command "xprop WM_CLASS" and click the window

br -a mpv state=tiled follow off
br -a tint2 state=floating follow off
br -a Lxappearance state=floating follow off
br -a Zathura state=tiled follow off
br -a zoom desktop='^5' follow off
br -a Microsoft\ Teams\ -\ Insiders:\* state=tiled desktop='^5' follow off
br -a kitty desktop='^6'follow off
br -a Nemo desktop='^3' follow off
br -a Code desktop='^4' follow off
br -a org.gnome.Nautilus desktop='^3' follow off
br -a firefox desktop='^1' follow off
br -a Brave-browser desktop='^1' follow off
br -a krita desktop='^7' follow off
#br -a Joplin desktop='^2'
